# Generated by Django 4.2.13 on 2024-06-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='categories',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categories', verbose_name='Категория'),
        ),
    ]
