# Generated by Django 4.2.13 on 2024-06-03 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_subcategories_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='services',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subcategories', verbose_name='Подкатегория'),
        ),
    ]
