# Generated by Django 4.2.13 on 2024-06-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_subcategories_categories_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='services',
        ),
        migrations.AddField(
            model_name='buyer',
            name='services',
            field=models.ManyToManyField(to='main.services', verbose_name='Услуги'),
        ),
    ]
